version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server 
    ports:
      - "8080:8080" # client port
      - "9002:9002" # front office port
    environment:
      - CLIENT_PORT=8080
      - FRONTEND_WEBSOCKET_PORT=9002
    env_file:
      - server.env
      
  # client_one:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client  # Vous pouvez créer un autre Dockerfile pour le client si nécessaire
  #   depends_on:
  #     - server  # Le client dépend du serveur

  # client_two:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client  # Vous pouvez créer un autre Dockerfile pour le client si nécessaire
  #   depends_on:
  #     - server  # Le client dépend du serveur